### ISSUE TITLE
My "person" is sick questions

### ISSUE THREAD

**Issue by DianeGutiw** [bcgov/covid19#4]
**What's the question**
My husband is sick
My roommate is sick
My coworker is sick
My son is sick
My daughter is sick
My child is sick

Describe the question
When you type in a question on a third person being sick without asking also if you should self isolate or adding "what should I do" the answer is currently giving information on what to do for your dog.

If you type "My child is sick: the bot does not understand and gives the "I do not understand call 911 if this is an emergency"

**What should the answer be**

The answer should be the same as if you ask "My son is sick what should I do" that question gives a detailed response on who should be tested and how to isolate.  

Describe the answer clearly.

**Other ways of asking the question.**
My husband is sick
My roommate is sick
My coworker is sick
My son is sick
My daughter is sick
My child is sick
May parent is sick
My grandmother is sick
My grandfather is sick
My uncle is sick
My aunt is sick
My family is sick
My neighbour is sick

**Comment by thorwolpert** [comment]
I made an Entity (person-nouns) and attached that to the training phrase "my wife i sick".
This should now return the correct response.
